-- =====================================================
-- Fixtures pour Cinescope
-- Mot de passe pour tous les users : password
-- =====================================================

-- Suppression des tables existantes (dans l'ordre des dépendances)
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS film_platforme;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS platforme;
DROP TABLE IF EXISTS user;
SET FOREIGN_KEY_CHECKS = 1;

-- =====================================================
-- Création des tables
-- =====================================================
CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(180) NOT NULL UNIQUE,
    roles JSON NOT NULL,
    password VARCHAR(255) NOT NULL,
    avatar VARCHAR(255) NULL
);

CREATE TABLE platforme (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    logo VARCHAR(255) NULL
);

CREATE TABLE film (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    synopsis TEXT NULL,
    release_year INT NOT NULL
);

CREATE TABLE film_platforme (
    film_id INT NOT NULL,
    platforme_id INT NOT NULL,
    PRIMARY KEY (film_id, platforme_id),
    FOREIGN KEY (film_id) REFERENCES film(id) ON DELETE CASCADE,
    FOREIGN KEY (platforme_id) REFERENCES platforme(id) ON DELETE CASCADE
);

-- =====================================================
-- USERS
-- Hash bcrypt 2y pour "password"
-- =====================================================
INSERT INTO user (id, email, roles, password, avatar) VALUES
(1, 'admin@cinescope.fr', '["ROLE_ADMIN"]', '$2y$13$igJtNm9qJBhfX/7LbTDvzu9t/hSX1hQs65Zp5g4.r63fjOoTejLNO', 'avatar_admin.png'),
(2, 'john.doe@email.com', '["ROLE_USER"]', '$2y$13$igJtNm9qJBhfX/7LbTDvzu9t/hSX1hQs65Zp5g4.r63fjOoTejLNO', 'avatar_john.png'),
(3, 'jane.smith@email.com', '["ROLE_USER"]', '$2y$13$igJtNm9qJBhfX/7LbTDvzu9t/hSX1hQs65Zp5g4.r63fjOoTejLNO', NULL),
(4, 'pierre.dupont@email.com', '["ROLE_USER"]', '$2y$13$igJtNm9qJBhfX/7LbTDvzu9t/hSX1hQs65Zp5g4.r63fjOoTejLNO', 'avatar_pierre.png'),
(5, 'marie.martin@email.com', '["ROLE_USER"]', '$2y$13$igJtNm9qJBhfX/7LbTDvzu9t/hSX1hQs65Zp5g4.r63fjOoTejLNO', NULL);

-- =====================================================
-- PLATFORMES
-- name utilise l'enum TypeMedia (valeurs: Netflix, Disney, Amazon, Canal, Ocs, Apple, Hbo, Youtube, Mytf1, Salto)
-- =====================================================
INSERT INTO platforme (id, name, url, logo) VALUES
(1, 'Netflix', 'https://www.netflix.com', '/images/platforms/netflix_logo.svg'),
(2, 'Disney', 'https://www.disneyplus.com', '/images/platforms/disney_logo.svg'),
(3, 'Amazon', 'https://www.primevideo.com', '/images/platforms/amazon_logo.svg'),
(4, 'Canal', 'https://www.canalplus.com', '/images/platforms/canal_logo.svg'),
(5, 'Ocs', 'https://www.ocs.fr', '/images/platforms/ocs_logo.svg'),
(6, 'Apple', 'https://tv.apple.com', '/images/platforms/apple_logo.svg'),
(7, 'Hbo', 'https://www.hbo.com', '/images/platforms/hbo_logo.svg'),
(8, 'Youtube', 'https://www.youtube.com', '/images/platforms/youtube_logo.svg');


-- =====================================================
-- FILMS
-- =====================================================
INSERT INTO film (id, title, synopsis, release_year) VALUES
(1, 'Inception', 'Un voleur qui s''infiltre dans les rêves des autres pour voler leurs secrets se voit offrir une chance de rédemption.', 2010),
(2, 'The Dark Knight', 'Batman affronte le Joker, un criminel anarchiste qui plonge Gotham dans le chaos.', 2008),
(3, 'Interstellar', 'Une équipe d''explorateurs voyage à travers un trou de ver dans l''espace pour assurer la survie de l''humanité.', 2014),
(4, 'Pulp Fiction', 'Les vies de deux tueurs à gages, d''un boxeur et d''un gangster s''entremêlent dans quatre histoires de violence et de rédemption.', 1994),
(5, 'The Matrix', 'Un hacker découvre que la réalité telle qu''il la connaît est une simulation créée par des machines.', 1999),
(6, 'Forrest Gump', 'L''histoire d''un homme simple qui se retrouve au cœur des moments clés de l''histoire américaine.', 1994),
(7, 'Le Seigneur des Anneaux: La Communauté de l''Anneau', 'Un jeune hobbit entreprend un voyage épique pour détruire un anneau maléfique.', 2001),
(8, 'Gladiator', 'Un général romain trahi est réduit en esclavage et devient gladiateur pour se venger de l''empereur.', 2000),
(9, 'Avatar', 'Un marine paraplégique est envoyé sur la lune Pandora où il se lie avec les Na''vi.', 2009),
(10, 'Titanic', 'Une histoire d''amour tragique à bord du paquebot Titanic lors de son voyage inaugural.', 1997),
(11, 'The Shawshank Redemption', 'Un banquier condamné à tort se lie d''amitié avec un autre détenu tout en planifiant son évasion.', 1994),
(12, 'Fight Club', 'Un employé de bureau insomniaque forme un club de combat clandestin avec un vendeur de savon charismatique.', 1999),
(13, 'Parasite', 'Une famille pauvre s''infiltre dans la vie d''une famille riche avec des conséquences dramatiques.', 2019),
(14, 'Joker', 'L''histoire des origines du célèbre méchant de Batman dans un Gotham City en déclin.', 2019),
(15, 'Dune', 'Paul Atréides doit voyager vers la planète la plus dangereuse de l''univers pour assurer l''avenir de sa famille.', 2021);
INSERT INTO film (id, title, synopsis, release_year) VALUES

(16, 'Echoes of Eternity', 'A timeless tale of love and discovery across parallel worlds.', 1995),
(17, 'Shadows of the Forgotten', 'An archaeologist uncovers ancient secrets that inspire modern innovation.', 2002),
(18, 'Whispers in the Wind', 'A young detective solves mysteries guided by gentle breezes.', 2010),
(19, 'Galactic Odyssey', 'Explorers journey through the cosmos to find a harmonious civilization.', 2015),
(20, 'The Last Symphony', 'A composer''s final masterpiece reveals beautiful hidden truths.', 1988),
(21, 'Crimson Horizon', 'Adventurers explore a vibrant landscape for new horizons.', 2007),
(22, 'Mystic Waters', 'Divers discover a submerged city with wondrous powers.', 2018),
(23, 'Fury of the Storm', 'A meteorologist predicts a storm that brings positive change.', 1999),
(24, 'Silent Guardians', 'Protectors safeguard the world from unseen challenges.', 2012),
(25, 'Enchanted Realms', 'A fantasy world where magic and reality blend harmoniously.', 2005),
(26, 'Rogue Elements', 'A scientist experiments with elements that lead to breakthroughs.', 2020),
(27, 'Veil of Deception', 'Explorers navigate illusions in a quest for truth.', 2013),
(28, 'Celestial Dreams', 'Astronauts dream of peaceful colonization of distant planets.', 2009),
(29, 'Phantom Echo', 'A researcher faces echoes of the past for inspiration.', 1997),
(30, 'Iron Resolve', 'A craftsman forges tools for an epic journey.', 2016),
(31, 'Lunar Legacy', 'Moon explorers inherit a legacy of ancient wisdom.', 2021),
(32, 'Cursed Chronicles', 'Historians decode a mysterious book that enriches history.', 2004),
(33, 'Blazing Trails', 'Pioneers create new paths in uncharted territories.', 1985),
(34, 'Quantum Quandary', 'Physicists unravel mysteries of quantum reality.', 2019),
(35, 'Savage Seas', 'Sailors navigate vast oceans for hidden treasures.', 1992),
(36, 'Eternal Flame', 'A love story that endures through time.', 2008),
(37, 'Frozen Abyss', 'Explorers delve into the depths of a frozen ocean.', 2014),
(38, 'Rebel Hearts', 'Dreamers fight for freedom in a hopeful regime.', 2022),
(39, 'Mystic Mirage', 'Illusions guide adventurers to beautiful discoveries.', 1998),
(40, 'Thunderous Roar', 'A naturalist observes nature''s powerful wonders.', 2006),
(41, 'Cosmic Collision', 'Scientists study asteroids in a quest for knowledge.', 2017),
(42, 'Phantom Phoenix', 'A mythical bird inspires renewal and hope.', 1996),
(43, 'Silent Storm', 'A quiet town embraces a transformative event.', 2011),
(44, 'Enigmatic Enclave', 'Scientists study a mysterious community for insights.', 2003),
(45, 'Blazing Comet', 'A comet''s path inspires human destiny.', 2023),
(46, 'Veiled Visions', 'Visionaries foresee events that shape the future.', 1994),
(47, 'Galactic Guardians', 'Heroes protect the galaxy with unity.', 2015),
(48, 'Crimson Tide', 'Naval explorers navigate oceans for exploration.', 2001),
(49, 'Mystic Meadows', 'Farmers discover wonders in their fields.', 2009),
(50, 'Fury Unleashed', 'A traveler unleashes creativity and passion.', 2018),
(51, 'Echoing Halls', 'Explorers navigate grand halls filled with history.', 1993),
(52, 'Celestial Symphony', 'Musicians compose inspired by the stars.', 2020),
(53, 'Phantom Fleet', 'Ships sail seas with tales of adventure.', 2007),
(54, 'Iron Citadel', 'Builders create fortresses for protection.', 2012),
(55, 'Lunar Labyrinth', 'Caves on the moon hold fascinating secrets.', 1999),
(56, 'Cursed Crown', 'A crown symbolizes a legacy of wisdom.', 2005),
(57, 'Blazing Inferno', 'Firefighters protect communities from challenges.', 2016),
(58, 'Quantum Quest', 'Scientists seek the ultimate understanding.', 1997),
(59, 'Savage Shores', 'Survivors adapt on a wild island.', 2010),
(60, 'Eternal Echo', 'Voices from the past inspire the present.', 2021),
(61, 'Frozen Frontier', 'Explorers cross icy lands for discovery.', 2004),
(62, 'Rebel Rising', 'Innovators rise against outdated ideas.', 1989),
(63, 'Mystic Monsoon', 'Rains bring joyful events to a village.', 2013),
(64, 'Thunderclap', 'A storm reveals ancient wonders.', 2008),
(65, 'Cosmic Cascade', 'Waterfalls inspire planetary harmony.', 2019),
(66, 'Phantom Pulse', 'Rhythms guide a journey of discovery.', 1995),
(67, 'Silent Sanctuary', 'A refuge protects and nurtures life.', 2022),
(68, 'Enigmatic Eclipse', 'An eclipse reveals hidden potentials.', 2002),
(69, 'Blazing Beacon', 'A light signals hope and guidance.', 2014),
(70, 'Veiled Vortex', 'Winds create paths to new dimensions.', 1998),
(71, 'Galactic Gambit', 'Beings engage in a game of cosmic strategy.', 2006),
(72, 'Crimson Crusade', 'Knights embark on a quest for knowledge.', 2017),
(73, 'Mystic Mirage', 'Desert visions lead to enlightening journeys.', 1996),
(74, 'Fury Forged', 'Craftsmen create legendary tools.', 2011),
(75, 'Echoing Eternity', 'Time reveals the beauty of life.', 2000),
(76, 'Whispering Woods', 'Forests share secrets of nature.', 2015),
(77, 'Stellar Symphony', 'Stars compose a melody of the universe.', 2023),
(78, 'Azure Abyss', 'Oceans hold depths of wonder.', 1990),
(79, 'Radiant Realm', 'A world glows with inner light.', 2008),
(80, 'Serene Summit', 'Mountains offer peaks of peace.', 2016),
(81, 'Luminous Labyrinth', 'Mazes light the way to treasures.', 1997),
(82, 'Harmonic Horizon', 'Horizons blend in perfect balance.', 2021),
(83, 'Velvet Vortex', 'Swirls lead to soft discoveries.', 2004),
(84, 'Golden Grove', 'Trees bear fruits of wisdom.', 2012),
(85, 'Tranquil Tide', 'Waves bring calm and renewal.', 1998),
(86, 'Emerald Echo', 'Greens resonate with life.', 2019),
(87, 'Sapphire Sky', 'Heavens inspire boundless dreams.', 2005),
(88, 'Crimson Cascade', 'Falls flow with vibrant energy.', 2017),
(89, 'Amber Aura', 'Glows surround with warmth.', 1994),
(90, 'Ivory Illusion', 'Dreams create beautiful realities.', 2020),
(91, 'Jade Journey', 'Paths lead to green paradises.', 2009),
(92, 'Pearl Paradox', 'Mysteries unfold like treasures.', 2013),
(93, 'Ruby Radiance', 'Lights shine with passion.', 1996),
(94, 'Onyx Odyssey', 'Dark paths reveal hidden lights.', 2022),
(95, 'Topaz Trail', 'Journeys sparkle with adventure.', 2007),
(96, 'Quartz Quest', 'Crystals guide to clarity.', 2014),
(97, 'Opal Oasis', 'Deserts bloom with color.', 1999),
(98, 'Diamond Dream', 'Gems inspire eternal hopes.', 2018),
(99, 'Garnet Gateway', 'Doors open to new worlds.', 2003),
(100, 'Amethyst Aura', 'Purples envelop in mystery.', 2021),
(101, 'Beryl Breeze', 'Winds carry gentle messages.', 1995),
(102, 'Coral Cove', 'Seashells hide oceanic secrets.', 2010),
(103, 'Feldspar Flight', 'Flights soar through skies.', 2006),
(104, 'Gypsum Glow', 'Soft lights illuminate paths.', 2015),
(105, 'Hematite Harmony', 'Balances create unity.', 1992),
(106, 'Jasper Journey', 'Stones mark epic travels.', 2023),
(107, 'Kyanite Key', 'Keys unlock cosmic doors.', 2008),
(108, 'Lapis Labyrinth', 'Blues weave intricate tales.', 2016),
(109, 'Malachite Meadow', 'Fields grow with vibrant life.', 1997),
(110, 'Nephrite Nexus', 'Connections link all things.', 2020),
(111, 'Obsidian Oracle', 'Prophecies guide with wisdom.', 2004),
(112, 'Pyrite Promise', 'Promises shine like gold.', 2012),
(113, 'Quartzite Quest', 'Quests seek inner strength.', 1998),
(114, 'Rhodonite Realm', 'Realms foster compassion.', 2019),
(115, 'Sodalite Sky', 'Skies inspire deep thoughts.', 2005),
(116, 'Tanzanite Tide', 'Tides bring waves of change.', 2017),
(117, 'Ulexite Universe', 'Universes reflect infinite beauty.', 1994),
(118, 'Vivianite Voyage', 'Voyages explore inner depths.', 2022),
(119, 'Wulfenite Whisper', 'Whispers share ancient lore.', 2007),
(120, 'Xenotime Xanadu', 'Paradises offer eternal bliss.', 2014),
(121, 'Yttrium Yarn', 'Stories weave through time.', 1999),
(122, 'Zircon Zenith', 'Peaks reach ultimate heights.', 2018),
(123, 'Alabaster Arc', 'Arcs span creative horizons.', 2003),
(124, 'Basalt Bridge', 'Bridges connect distant lands.', 2021),
(125, 'Chert Chronicle', 'Chronicles record timeless tales.', 1995),
(126, 'Dolomite Dream', 'Dreams build lasting foundations.', 2010),
(127, 'Epidote Essence', 'Essences capture pure joy.', 2006),
(128, 'Fluorite Fantasy', 'Fantasies color the imagination.', 2015),
(129, 'Galena Galaxy', 'Galaxies swirl with wonder.', 1992),
(130, 'Halite Haven', 'Havens provide salty wisdom.', 2023),
(131, 'Illite Illusion', 'Illusions teach valuable lessons.', 2008),
(132, 'Jadeite Jewel', 'Jewels adorn the soul.', 2016),
(133, 'Kernite Kingdom', 'Kingdoms thrive in harmony.', 1997),
(134, 'Limonite Light', 'Lights guide through darkness.', 2020),
(135, 'Magnetite Magic', 'Magic attracts positive forces.', 2004),
(136, 'Natrolite Nexus', 'Nexuses link hearts and minds.', 2012),
(137, 'Olivine Oasis', 'Oases bloom in arid lands.', 1998),
(138, 'Petalite Path', 'Paths lead to peaceful resolutions.', 2019),
(139, 'Quartz Quest', 'Quests uncover hidden gems.', 2005),
(140, 'Rutile Radiance', 'Radiance illuminates truths.', 2017),
(141, 'Spinel Spark', 'Sparks ignite creativity.', 1994),
(142, 'Talc Tale', 'Tales soften hard realities.', 2022),
(143, 'Uvarovite Unity', 'Unity brings strength.', 2007),
(144, 'Vesuvianite Vision', 'Visions foresee beauty.', 2014),
(145, 'Willemite Wonder', 'Wonders fill the world.', 1999),
(146, 'Xanthophyll Xanadu', 'Xanadus offer colorful escapes.', 2018),
(147, 'Ytterbium Yarn', 'Yarns spin hopeful futures.', 2003),
(148, 'Zoisite Zenith', 'Zeniths achieve perfect balance.', 2021),
(149, 'Agate Arcana', 'Arcana reveal mystical secrets.', 1995),
(150, 'Beryl Beacon', 'Beacons signal safe harbors.', 2010),
(151, 'Calcite Cascade', 'Cascades flow with clarity.', 2006),
(152, 'Danburite Dream', 'Dreams soar to new heights.', 2015),
(153, 'Eudialyte Essence', 'Essences embody vitality.', 1992),
(154, 'Fuchsite Fantasy', 'Fantasies heal the spirit.', 2023),
(155, 'Goshenite Glow', 'Glows radiate inner peace.', 2008),
(156, 'Howlite Harmony', 'Harmony calms the soul.', 2016),
(157, 'Idocrase Insight', 'Insights deepen understanding.', 1997),
(158, 'Jasper Jewel', 'Jewels symbolize enduring love.', 2020),
(159, 'Kunzite Kingdom', 'Kingdoms foster growth.', 2004),
(160, 'Larimar Light', 'Lights brighten dark paths.', 2012),
(161, 'Morganite Magic', 'Magic enhances connections.', 1998),
(162, 'Nuummite Nexus', 'Nexuses unite energies.', 2019),
(163, 'Oceanite Oasis', 'Oases provide refreshing respite.', 2005),
(164, 'Peridot Path', 'Paths lead to joyful discoveries.', 2017),
(165, 'Qingsongite Quest', 'Quests inspire perseverance.', 1994),
(166, 'Rhodochrosite Radiance', 'Radiance promotes self-love.', 2022),
(167, 'Seraphinite Spark', 'Sparks awaken potential.', 2007),
(168, 'Thulite Tale', 'Tales teach compassion.', 2014),
(169, 'Uvite Unity', 'Unity creates lasting bonds.', 1999),
(170, 'Variscite Vision', 'Visions guide ethical choices.', 2018),
(171, 'Wavellite Wonder', 'Wonders expand horizons.', 2003),
(172, 'Xonotlite Xanadu', 'Xanadus inspire tranquility.', 2021),
(173, 'Yugawaralite Yarn', 'Yarns weave community stories.', 1995),
(174, 'Zektzerite Zenith', 'Zeniths represent achievement.', 2010),
(175, 'Aventurine Arc', 'Arcs curve towards success.', 2006),
(176, 'Bloodstone Beacon', 'Beacons offer courage.', 2015),
(177, 'Carnelian Cascade', 'Cascades energize the spirit.', 1992),
(178, 'Dumortierite Dream', 'Dreams build confidence.', 2023),
(179, 'Elbaite Essence', 'Essences capture joy.', 2008),
(180, 'Feldspathoid Fantasy', 'Fantasies spark innovation.', 2016),
(181, 'Gahnite Glow', 'Glows illuminate possibilities.', 1997),
(182, 'Hauyne Harmony', 'Harmony balances energies.', 2020),
(183, 'Iolite Insight', 'Insights reveal inner truths.', 2004),
(184, 'Jet Jewel', 'Jewels protect and empower.', 2012),
(185, 'Kyanite Kingdom', 'Kingdoms promote equality.', 1998),
(186, 'Labradorite Light', 'Lights reveal hidden strengths.', 2019),
(187, 'Magnesite Magic', 'Magic fosters creativity.', 2005),
(188, 'Narsarsukite Nexus', 'Nexuses connect minds.', 2017),
(189, 'Okenite Oasis', 'Oases nurture growth.', 1994),
(190, 'Piemontite Path', 'Paths encourage exploration.', 2022),
(191, 'Quebecite Quest', 'Quests seek wisdom.', 2007),
(192, 'Riebeckite Radiance', 'Radiance inspires hope.', 2014),
(193, 'Sillimanite Spark', 'Sparks ignite passions.', 1999),
(194, 'Tugtupite Tale', 'Tales celebrate diversity.', 2018),
(195, 'Ussingite Unity', 'Unity strengthens communities.', 2003),
(196, 'Vlasovite Vision', 'Visions promote peace.', 2021),
(197, 'Wadeite Wonder', 'Wonders fuel curiosity.', 1995),
(198, 'Xenophyllite Xanadu', 'Xanadus offer serenity.', 2010),
(199, 'Yofortierite Yarn', 'Yarns connect generations.', 2006),
(200, 'Zunyite Zenith', 'Zeniths symbolize enlightenment.', 2015),
(201, 'Albite Arcana', 'Arcana unlock potentials.', 1992),
(202, 'Biotite Beacon', 'Beacons guide explorers.', 2023),
(203, 'Cordierite Cascade', 'Cascades clear the mind.', 2008),
(204, 'Datolite Dream', 'Dreams inspire action.', 2016),
(205, 'Ekanite Essence', 'Essences embody purity.', 1997),
(206, 'Fayalite Fantasy', 'Fantasies enrich lives.', 2020),
(207, 'Glaucophane Glow', 'Glows signal new beginnings.', 2004),
(208, 'Hedenbergite Harmony', 'Harmony restores balance.', 2012),
(209, 'Ilmenite Insight', 'Insights foster empathy.', 1998),
(210, 'Johannsenite Jewel', 'Jewels represent beauty.', 2019),
(211, 'Kalsilite Kingdom', 'Kingdoms value cooperation.', 2005),
(212, 'Lazulite Light', 'Lights reveal wisdom.', 2017),
(213, 'Muscovite Magic', 'Magic enhances intuition.', 1994),
(214, 'Nepheline Nexus', 'Nexuses link possibilities.', 2022),
(215, 'Orthoclase Oasis', 'Oases provide inspiration.', 2007),
(216, 'Pargasite Path', 'Paths lead to fulfillment.', 2014),
(217, 'Quenstedtite Quest', 'Quests build resilience.', 1999),
(218, 'Rhodonite Radiance', 'Radiance promotes kindness.', 2018),
(219, 'Sanidine Spark', 'Sparks encourage growth.', 2003),
(220, 'Tremolite Tale', 'Tales honor traditions.', 2021),
(221, 'Uralite Unity', 'Unity creates harmony.', 1995),
(222, 'Vermiculite Vision', 'Visions expand awareness.', 2010),
(223, 'Wollastonite Wonder', 'Wonders inspire awe.', 2006),
(224, 'Xanthoconite Xanadu', 'Xanadus foster peace.', 2015),
(225, 'Yttrotantalite Yarn', 'Yarns weave dreams.', 1992),
(226, 'Zoisite Zenith', 'Zeniths achieve goals.', 2023),
(227, 'Anorthite Arc', 'Arcs represent journeys.', 2008),
(228, 'Bytownite Beacon', 'Beacons offer direction.', 2016),
(229, 'Clinopyroxene Cascade', 'Cascades refresh spirits.', 1997),
(230, 'Diopside Dream', 'Dreams fuel ambitions.', 2020),
(231, 'Enstatite Essence', 'Essences capture essence.', 2004),
(232, 'Ferrosilite Fantasy', 'Fantasies spark joy.', 2012),
(233, 'Gehlenite Glow', 'Glows illuminate futures.', 1998),
(234, 'Hessite Harmony', 'Harmony aligns energies.', 2019),
(235, 'Indialite Insight', 'Insights deepen bonds.', 2005),
(236, 'Jervisite Jewel', 'Jewels symbolize strength.', 2017),
(237, 'Koenenite Kingdom', 'Kingdoms promote unity.', 1994),
(238, 'Labuntsovite Light', 'Lights guide decisions.', 2022),
(239, 'Mawsonite Magic', 'Magic reveals truths.', 2007),
(240, 'Nacrite Nexus', 'Nexuses connect worlds.', 2014),
(241, 'Osumilite Oasis', 'Oases inspire creativity.', 1999),
(242, 'Piemontite Path', 'Paths encourage growth.', 2018),
(243, 'Quartz Quest', 'Quests seek balance.', 2003),
(244, 'Rutile Radiance', 'Radiance boosts confidence.', 2021),
(245, 'Spodumene Spark', 'Sparks ignite ideas.', 1995),
(246, 'Tektite Tale', 'Tales share knowledge.', 2010),
(247, 'Ulvospinel Unity', 'Unity fosters progress.', 2006),
(248, 'Vesuvianite Vision', 'Visions promote understanding.', 2015),
(249, 'Willemite Wonder', 'Wonders expand minds.', 1992),
(250, 'Xonotlite Xanadu', 'Xanadus offer bliss.', 2023),
(251, 'Yugawaralite Yarn', 'Yarns connect hearts.', 2008),
(252, 'Zektzerite Zenith', 'Zeniths inspire achievement.', 2016),
(253, 'Aventurine Arc', 'Arcs lead to success.', 1997),
(254, 'Bloodstone Beacon', 'Beacons provide courage.', 2020),
(255, 'Carnelian Cascade', 'Cascades energize.', 2004),
(256, 'Dumortierite Dream', 'Dreams build futures.', 2012),
(257, 'Elbaite Essence', 'Essences embody happiness.', 1998),
(258, 'Feldspathoid Fantasy', 'Fantasies enrich.', 2019),
(259, 'Gahnite Glow', 'Glows light paths.', 2005),
(260, 'Hauyne Harmony', 'Harmony balances.', 2017),
(261, 'Iolite Insight', 'Insights reveal.', 1994),
(262, 'Jet Jewel', 'Jewels empower.', 2022),
(263, 'Kyanite Kingdom', 'Kingdoms unite.', 2007),
(264, 'Labradorite Light', 'Lights strengthen.', 2014),
(265, 'Magnesite Magic', 'Magic creates.', 1999),
(266, 'Narsarsukite Nexus', 'Nexuses link.', 2018),
(267, 'Okenite Oasis', 'Oases nurture.', 2003),
(268, 'Piemontite Path', 'Paths explore.', 2021),
(269, 'Quebecite Quest', 'Quests learn.', 1995),
(270, 'Riebeckite Radiance', 'Radiance hopes.', 2010),
(271, 'Sillimanite Spark', 'Sparks passion.', 2006),
(272, 'Tugtupite Tale', 'Tales celebrate.', 2015),
(273, 'Ussingite Unity', 'Unity strengthens.', 1992),
(274, 'Vlasovite Vision', 'Visions peace.', 2023),
(275, 'Wadeite Wonder', 'Wonders curiosity.', 2008),
(276, 'Xenophyllite Xanadu', 'Xanadus serenity.', 2016),
(277, 'Yofortierite Yarn', 'Yarns generations.', 1997),
(278, 'Zunyite Zenith', 'Zeniths enlightenment.', 2020),
(279, 'Albite Arcana', 'Arcana potentials.', 2004),
(280, 'Biotite Beacon', 'Beacons explorers.', 2012),
(281, 'Cordierite Cascade', 'Cascades mind.', 1998),
(282, 'Datolite Dream', 'Dreams action.', 2019),
(283, 'Ekanite Essence', 'Essences purity.', 2005),
(284, 'Fayalite Fantasy', 'Fantasies lives.', 2017),
(285, 'Glaucophane Glow', 'Glows beginnings.', 1994),
(286, 'Hedenbergite Harmony', 'Harmony balance.', 2022),
(287, 'Ilmenite Insight', 'Insights empathy.', 2007),
(288, 'Johannsenite Jewel', 'Jewels beauty.', 2014),
(289, 'Kalsilite Kingdom', 'Kingdoms cooperation.', 1999),
(290, 'Lazulite Light', 'Lights wisdom.', 2018),
(291, 'Muscovite Magic', 'Magic intuition.', 2003),
(292, 'Nepheline Nexus', 'Nexuses possibilities.', 2021),
(293, 'Orthoclase Oasis', 'Oases inspiration.', 1995),
(294, 'Pargasite Path', 'Paths fulfillment.', 2010),
(295, 'Quenstedtite Quest', 'Quests resilience.', 2006),
(296, 'Rhodonite Radiance', 'Radiance kindness.', 2015),
(297, 'Sanidine Spark', 'Sparks growth.', 1992),
(298, 'Tremolite Tale', 'Tales traditions.', 2023),
(299, 'Uralite Unity', 'Unity harmony.', 2008),
(300, 'Vermiculite Vision', 'Visions awareness.', 2016),
(301, 'Wollastonite Wonder', 'Wonders awe.', 1997),
(302, 'Xanthoconite Xanadu', 'Xanadus peace.', 2020),
(303, 'Yttrotantalite Yarn', 'Yarns dreams.', 2004),
(304, 'Zoisite Zenith', 'Zeniths goals.', 2012),
(305, 'Anorthite Arc', 'Arcs journeys.', 1998),
(306, 'Bytownite Beacon', 'Beacons direction.', 2019),
(307, 'Clinopyroxene Cascade', 'Cascades spirits.', 2005),
(308, 'Diopside Dream', 'Dreams ambitions.', 2017),
(309, 'Enstatite Essence', 'Essences essence.', 1994),
(310, 'Ferrosilite Fantasy', 'Fantasies joy.', 2022),
(311, 'Gehlenite Glow', 'Glows futures.', 2007),
(312, 'Hessite Harmony', 'Harmony energies.', 2014),
(313, 'Indialite Insight', 'Insights bonds.', 1999),
(314, 'Jervisite Jewel', 'Jewels strength.', 2018),
(315, 'Koenenite Kingdom', 'Kingdoms unity.', 2003);
-- =====================================================
-- FILM_PLATFORME (table de liaison ManyToMany)
-- =====================================================
INSERT INTO film_platforme (film_id, platforme_id) VALUES
-- Inception sur Netflix et Amazon
(1, 1), (1, 3),
-- The Dark Knight sur Netflix, Amazon et Canal
(2, 1), (2, 3), (2, 4),
-- Interstellar sur Amazon et Apple
(3, 3), (3, 6),
-- Pulp Fiction sur Netflix et OCS
(4, 1), (4, 5),
-- The Matrix sur Netflix, Amazon et HBO
(5, 1), (5, 3), (5, 7),
-- Forrest Gump sur Amazon et Disney
(6, 3), (6, 2),
-- Le Seigneur des Anneaux sur Canal et OCS
(7, 4), (7, 5),
-- Gladiator sur Amazon et Canal
(8, 3), (8, 4),
-- Avatar sur Disney et Canal
(9, 2), (9, 4),
-- Titanic sur Disney et Netflix
(10, 2), (10, 1),
-- The Shawshank Redemption sur Netflix et Amazon
(11, 1), (11, 3),
-- Fight Club sur Amazon et OCS
(12, 3), (12, 5),
-- Parasite sur Netflix et Canal
(13, 1), (13, 4),
-- Joker sur HBO et OCS
(14, 7), (14, 5),
-- Dune sur HBO et Amazon
(15, 7), (15, 3);